name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/rust.yml
      - backend/**
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
        with:
          # Change CACHE_VERSION to clear cache
          key: ${{ secrets.CACHE_VERSION }}
          working-directory: backend
      - name: Build
        run: cargo build --verbose --release
        working-directory: backend
      - name: Run tests
        run: cargo test --verbose --release
        working-directory: backend
