name: Backend CD

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/backend-cd.yml
      - backend/**
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, linux] # docker login doesn't work on Windows right now https://github.com/docker/login-action/issues/47
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          context: backend
          tags: jeevcat/ledger-dash-backend:latest
          pull: true
          push: true

  deploy:
      name: Fly deploy
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
