# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/frontend-ci.yml
      - frontend/**
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install --frozen-lockfile
        working-directory: frontend
      - run: yarn lint
        working-directory: frontend
      - run: yarn build --if-present
        working-directory: frontend
